### ISSUE TITLE
Deprecated mysql extension

### ISSUE THREAD

**Issue by kyrnbs** [warhawk3407/bgpanel#21]
Deprecated: mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in bgpanel/includes/mysql.php on line 39

**Comment by Profforgr** [comment]
> Deprecated: mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in bgpanel/includes/mysql.php on line 39

No need to fix. MySQL will be available as extention to PHP. mysql_* should be available forever at PHP.

**Comment by superg2** [comment]
+1
PDO in next version of bgpanel v2.
